export const calculatorSections = [
  "background",
  "revenue",
  "expenses",
  "assets",
  "roa",
  "download",
];

export const navItems = ["home", "calculator", "about"];

export const copy = {
  zh: {
    brand: "ROA Insight",
    badge: "重卡运输经营分析工具",
    heroTitle: "重卡客户全生命周期ROA推导",
    heroBody: "Motor Sights Overseas",
    nav: {
      home: "首页",
      calculator: "ROA Calculator",
      about: "About",
    },
    sectionTitles: {
      background: "背景信息",
      revenue: "收入",
      expenses: "支出",
      assets: "资产",
      roa: "ROA",
      download: "下载",
    },
    save: "保存并计算",
    clear: "清空本页",
    remove: "删除",
    saved: "已保存到当前浏览器",
    cleared: "已清空当前页数据",
    language: "语言",
    currencyRateTitle: "汇率设置",
    currencyDisplay: "展示币种",
    rateHint: "仅在这里设置汇率与展示币种，收入、支出、资产页面不再单独换算。",
    exportExcel: "导出 Excel",
    exportHint: "导出为 Excel 表格数据，便于继续整理和发送。",
    homeCardTitle: "经营模型总览",
    homeCardBody: "围绕收入、支出、资产三层结构，完成重卡客户全生命周期 ROA 的可视化推导与导出。",
    homeCardNote: "支持中印双语、桌面与移动端适配，以及多视图 ROA 展示。",
    backgroundIntro: "补齐客户基础信息、组织架构与需求信息，作为方案推导和交付留档的统一底稿。",
    revenueIntro: "收入 = 运输单价 × 运营天数 × 单车装载量 × 单天车次 × 出勤率 × 车数",
    expensesIntro: "支出 = 折旧成本 + 人工成本 + 能源成本 + 配件成本 + 维修成本 + 轮胎成本 + 运维成本",
    assetsIntro: "资本 = 车辆资产 + 自建基础设施 + 配件资产 + 轮胎资产",
    roaIntro: "展示全生命周期核心参数，并可切换表格、柱状图、折线图。",
    downloadIntro: "导出背景信息、收入、支出、资产与 ROA 的 Excel 数据表。",
    aboutTitle: "开发者",
    email: "Email",
    wechat: "WeChat",
    headings: {
      basicInfo: "基础信息",
      infraInfo: "基础设施",
      contacts: "联络人",
      organization: "客户组织架构",
      customerNeeds: "客户需求信息",
      laborBase: "基础工种",
      laborExtra: "新增工种",
    },
    formulas: {
      revenue: "收入 = 运输单价 × 运营天数 × 单车装载量 × 单天车次 × 出勤率 × 车数",
      expense: "支出 = 折旧成本 + 人工成本 + 能源成本 + 配件成本 + 维修成本 + 轮胎成本 + 运维成本",
      asset: "资本 = 车辆资产 + 自建基础设施 + 配件资产 + 轮胎资产",
    },
    units: {
      day: "天",
      ton: "吨",
      year: "年",
      ratio: "比例",
      hour: "小时",
      distance: "公里",
      currencyPerTon: "元/吨",
    },
    energyType: {
      electric: "电",
      diesel: "油",
    },
    loadMode: {
      dimensions: "箱体长宽高计算",
      direct: "直接输入体积",
    },
    views: {
      table: "表格",
      bar: "柱状图",
      line: "折线图",
    },
    warnings: {
      title: "计算提醒",
      dailyTripsDivisor: "单趟往返时间不能为 0。",
      expectedTransportDaysDivisor: "预计运输天数不能为 0。",
      vehicleCountDivisor: "单车装载量或单天车次为 0，无法计算车数。",
      depreciationDivisor: "折旧年限不能为 0。",
      attendance: "单日有效工作时间为 0，出勤率无法计算。",
      roa: "资产为 0，ROA 无法计算。",
      lifecycleRoaDivisor: "4 年总资产为 0，全生命周期 ROA 无法计算。",
    },
    labels: {
      customerCompanyName: "客户公司名称",
      routeScenario: "线路 / 场景",
      routeDescription: "描述",
      operationSite: "运营场地",
      siteLocation: "位置",
      contactName: "联络人姓名",
      contactTitle: "联络人职务",
      contactPhone: "联络人电话",
      departmentDivision: "部门",
      organizationPosition: "岗位",
      organizationHeadcount: "人数",
      organizationAverageSalary: "平均薪资",
      requestDate: "需求提出时间",
      counterpart: "对接人",
      requestedVehicleType: "所需车辆种类",
      energyType: "能源类型",
      desiredConfig: "期望配置",
      concernsAndPainPoints: "客户关注点 & 痛点",
      expectedDeliveryDate: "期望交付时间",
      specialRequirements: "特殊需求",
      transportPrice: "运输单价",
      annualDowntimeDays: "不运营的天数",
      expectedTransportVolume: "预期运输量",
      expectedTransportDays: "预计运输天数",
      vehicleCountMode: "车数计算模式",
      manualVehicleCount: "手动车数",
      loadVolumeMode: "装载体积计算方式",
      cargoBoxLength: "箱体长",
      cargoBoxWidth: "箱体宽",
      cargoBoxHeight: "箱体高",
      directLoadVolume: "直接输入体积",
      materialDensity: "运输物料密度",
      roundTripHours: "单趟往返时间",
      morningMeeting: "早会时间",
      mealTime: "吃饭时间",
      restTime: "休息时间",
      shiftChangeTime: "换班时间",
      otherOperationIdle: "其他无效工作时间",
      loadingQueue: "装点排队",
      unloadingQueue: "卸点排队",
      yardQueue: "堆点排队",
      traffic: "堵车",
      fuelingOrCharging: "加油或换电/充电",
      otherTransitIdle: "其他在途无效时间",
      maintenanceHours: "单次维修时间",
      partsWaitHours: "配件等待时间",
      annualMaintenanceCounts: "单车年维修次数",
      purchasePrice: "采购价格",
      depreciationYears: "折旧年限",
      driverCount: "司机人数",
      driverSalary: "司机年度薪酬福利总包",
      technicianCount: "维修师人数",
      technicianSalary: "维修师年度薪酬福利总包",
      warehouseManagerCount: "仓库管理员人数",
      warehouseManagerSalary: "仓库管理员年度薪酬福利总包",
      extraRoleName: "新增工种名称",
      extraRoleCount: "新增工种人数",
      extraRoleSalary: "新增工种年度薪酬福利总包",
      kmEnergyUse: "公里能耗",
      energyPrice: "电价 / 能源单价",
      oneWayDistance: "单程距离",
      repairHoursPerVisit: "单次维修工时",
      repairUnitPrice: "维修单价 / 小时",
      repairFrequency: "年均维修次数",
      tireUnitPrice: "轮胎单价",
      tiresPerVehicle: "单车轮胎数量",
      tireReplacementFrequency: "轮胎更换频次",
      managementCount: "管理人员人数",
      managementSalary: "平均年包薪酬",
      facilityRent: "场地租赁年费",
      officeSpend: "办公室支出年费用",
      partsCostMode: "配件成本计算模式",
      annualPartsDirectCost: "每年配件预测成本",
      infrastructurePurchaseValue: "自建基础设施采购总值",
      infrastructureValue: "自建基础设施总值",
      partsSafetyRate: "配件安全库存比例",
      tireSafetyRate: "轮胎安全库存比例",
      infrastructureDepreciationYears: "基础设施折旧年限",
    },
    formulaCards: {
      operatingDays: "运营天数",
      payload: "单车装载量",
      dailyTrips: "单天车次",
      attendanceRate: "出勤率",
      vehicleCount: "车数",
      depreciationCost: "折旧成本",
      laborCost: "人工成本",
      energyCost: "能源成本",
      partsCost: "配件成本",
      repairCost: "维修成本",
      tireCost: "轮胎成本",
      operationCost: "运维成本",
      infraAsset: "自建基础设施",
      vehicleAsset: "车辆资产",
      partsAsset: "配件资产",
      tireAsset: "轮胎资产",
    },
    metrics: {
      operatingDays: "年运营天数",
      payload: "单车装载量",
      dailyTrips: "单天车次",
      attendanceRate: "出勤率",
      vehicleCount: "车数",
      annualRevenue: "4年总收入",
      totalExpense: "4年总支出",
      totalAssets: "4年总资产",
      lifecycleRoa: "全生命周期 ROA",
      loadVolume: "装载体积",
      effectiveDailyHours: "单日有效工作时间",
      expectedDailyDemand: "日均运输需求",
    },
    notes: {
      moneyUnit: "金额展示单位",
      report: "导出说明",
      roundUp: "车数已按向上取整处理",
      fixedInfra: "自建基础设施按 10 年直线折旧",
      averageAnnual: "按 4 年平均口径展示",
    },
    table: {
      year: "年份",
      revenue: "收入",
      expense: "支出",
      profit: "利润",
      assets: "资产",
      roa: "ROA",
      infrastructure: "自建基础设施净值",
      partsAsset: "配件资产",
      tireAsset: "轮胎资产",
      attendanceRate: "出勤率",
      annualTripsPerVehicle: "单车年车次",
      lifecycle: "全生命周期",
      parameter: "参数",
      value: "数值",
      revenueModel: "全生命周期收入测算图",
      costModel: "全生命周期成本测算",
      assetModel: "全生命周期资产测算图",
      roaModel: "全生命周期ROA测算",
      operationModel: "全生命周期运营效率与ROA图",
      lifecycleParams: "全生命周期关键参数总览",
    },
    groups: {
      revenuePricing: "运输单价与运量",
      revenueOperatingDays: "运营天数",
      revenuePayload: "单车装载量",
      revenueTrips: "单天车次",
      revenueAttendance: "出勤率",
      revenueVehicles: "车数",
      expenseDepreciation: "折旧成本",
      expenseLabor: "人工成本",
      expenseEnergy: "能源成本",
      expenseParts: "配件成本",
      expenseRepair: "维修成本",
      expenseTires: "轮胎成本",
      expenseOperations: "运维成本",
      assetInfra: "自建基础设施",
      assetVehicle: "车辆资产",
      assetParts: "配件资产",
      assetTires: "轮胎资产",
    },
    options: {
      calculated: "自动计算",
      manual: "手动输入",
      formula: "按配件明细计算",
      direct: "直接填写年度预测成本",
    },
    partRow: {
      name: "配件名称",
      quantity: "配件种类 / 数量",
      price: "配件价格",
      frequency: "使用频次",
      add: "新增配件",
      remove: "删除",
    },
    repeater: {
      addRoute: "新增线路 / 场景",
      addContact: "新增联系人",
      addOrg: "新增组织架构",
      addLaborRole: "新增工种",
    },
  },
  id: {
    brand: "ROA Insight",
    badge: "Alat Analisis Operasi Truk Berat",
    heroTitle: "Turunan ROA Siklus Hidup Pelanggan Truk Berat",
    heroBody: "Motor Sights Overseas",
    nav: {
      home: "Beranda",
      calculator: "ROA Calculator",
      about: "Tentang",
    },
    sectionTitles: {
      background: "Informasi Latar",
      revenue: "Pendapatan",
      expenses: "Biaya",
      assets: "Aset",
      roa: "ROA",
      download: "Unduh",
    },
    save: "Simpan dan Hitung",
    clear: "Kosongkan Halaman Ini",
    remove: "Hapus",
    saved: "Tersimpan di browser ini",
    cleared: "Data halaman ini telah dihapus",
    language: "Bahasa",
    currencyRateTitle: "Pengaturan Kurs",
    currencyDisplay: "Mata uang tampil",
    rateHint: "Atur kurs dan mata uang tampil hanya di sini.",
    exportExcel: "Ekspor Excel",
    exportHint: "Ekspor data tabel ke Excel agar mudah dilanjutkan dan dibagikan.",
    homeCardTitle: "Ringkasan Model Operasi",
    homeCardBody: "Menyatukan pendapatan, biaya, dan aset untuk menurunkan ROA sepanjang siklus hidup pelanggan truk berat.",
    homeCardNote: "Mendukung bilingual, responsif, serta beberapa mode tampilan ROA.",
    backgroundIntro: "Lengkapi informasi pelanggan, organisasi, dan kebutuhan proyek sebagai dasar analisis operasional.",
    revenueIntro: "Pendapatan = Tarif angkut × Hari operasi × Muatan per unit × Ritase harian × Tingkat kehadiran × Jumlah unit",
    expensesIntro: "Biaya = Depresiasi + Tenaga kerja + Energi + Suku cadang + Perawatan + Ban + Operasional",
    assetsIntro: "Modal = Aset kendaraan + Infrastruktur sendiri + Aset suku cadang + Aset ban",
    roaIntro: "Tampilkan parameter utama siklus hidup dan ubah tampilan tabel, batang, atau garis.",
    downloadIntro: "Ekspor informasi latar, pendapatan, biaya, aset, dan ROA ke tabel Excel.",
    aboutTitle: "Pengembang",
    email: "Email",
    wechat: "WeChat",
    headings: {
      basicInfo: "Informasi Dasar",
      infraInfo: "Infrastruktur",
      contacts: "Kontak",
      organization: "Struktur Organisasi Pelanggan",
      customerNeeds: "Kebutuhan Pelanggan",
      laborBase: "Kelompok Tenaga Kerja Dasar",
      laborExtra: "Kelompok Tenaga Kerja Tambahan",
    },
    formulas: {
      revenue: "Pendapatan = Tarif angkut × Hari operasi × Muatan per unit × Ritase harian × Tingkat kehadiran × Jumlah unit",
      expense: "Biaya = Depresiasi + Tenaga kerja + Energi + Suku cadang + Perawatan + Ban + Operasional",
      asset: "Modal = Aset kendaraan + Infrastruktur sendiri + Aset suku cadang + Aset ban",
    },
    units: {
      day: "hari",
      ton: "ton",
      year: "tahun",
      ratio: "rasio",
      hour: "jam",
      distance: "km",
      currencyPerTon: "RMB/ton",
    },
    energyType: {
      electric: "Listrik",
      diesel: "Solar",
    },
    loadMode: {
      dimensions: "Hitung dari panjang-lebar-tinggi",
      direct: "Input volume langsung",
    },
    views: {
      table: "Tabel",
      bar: "Bar",
      line: "Line",
    },
    warnings: {
      title: "Peringatan Perhitungan",
      dailyTripsDivisor: "Waktu pulang-pergi tidak boleh 0.",
      expectedTransportDaysDivisor: "Hari transportasi rencana tidak boleh 0.",
      vehicleCountDivisor: "Muatan per unit atau trip harian bernilai 0.",
      depreciationDivisor: "Masa depresiasi tidak boleh 0.",
      attendance: "Jam kerja efektif harian bernilai 0.",
      roa: "Aset bernilai 0 sehingga ROA tidak bisa dihitung.",
      lifecycleRoaDivisor: "Total aset 4 tahun bernilai 0.",
    },
    labels: {
      customerCompanyName: "Nama perusahaan pelanggan",
      routeScenario: "Rute / skenario",
      routeDescription: "Deskripsi",
      operationSite: "Lokasi operasional",
      siteLocation: "Lokasi",
      contactName: "Nama kontak",
      contactTitle: "Jabatan kontak",
      contactPhone: "Telepon kontak",
      departmentDivision: "Departemen",
      organizationPosition: "Posisi",
      organizationHeadcount: "Jumlah orang",
      organizationAverageSalary: "Gaji rata-rata",
      requestDate: "Tanggal kebutuhan",
      counterpart: "PIC pelanggan",
      requestedVehicleType: "Jenis kendaraan yang dibutuhkan",
      energyType: "Jenis energi",
      desiredConfig: "Konfigurasi yang diharapkan",
      concernsAndPainPoints: "Fokus perhatian & titik masalah pelanggan",
      expectedDeliveryDate: "Target waktu penyerahan",
      specialRequirements: "Kebutuhan khusus",
      transportPrice: "Tarif angkut",
      annualDowntimeDays: "Hari tidak beroperasi",
      expectedTransportVolume: "Target volume angkut",
      expectedTransportDays: "Hari operasi yang direncanakan",
      vehicleCountMode: "Mode perhitungan jumlah unit",
      manualVehicleCount: "Jumlah unit manual",
      loadVolumeMode: "Metode volume muat",
      cargoBoxLength: "Panjang bak",
      cargoBoxWidth: "Lebar bak",
      cargoBoxHeight: "Tinggi bak",
      directLoadVolume: "Volume langsung",
      materialDensity: "Densitas material",
      roundTripHours: "Waktu satu siklus perjalanan",
      morningMeeting: "Waktu briefing pagi",
      mealTime: "Waktu makan",
      restTime: "Waktu istirahat",
      shiftChangeTime: "Waktu pergantian shift",
      otherOperationIdle: "Waktu tidak efektif operasi lainnya",
      loadingQueue: "Antrean titik muat",
      unloadingQueue: "Antrean titik bongkar",
      yardQueue: "Antrean yard",
      traffic: "Macet",
      fuelingOrCharging: "Isi BBM / tukar baterai / isi daya",
      otherTransitIdle: "Waktu transit tidak efektif lainnya",
      maintenanceHours: "Durasi per servis",
      partsWaitHours: "Waktu tunggu suku cadang",
      annualMaintenanceCounts: "Frekuensi servis tahunan per unit",
      purchasePrice: "Harga pembelian",
      depreciationYears: "Masa depresiasi",
      driverCount: "Jumlah pengemudi",
      driverSalary: "Total kompensasi tahunan pengemudi",
      technicianCount: "Jumlah teknisi",
      technicianSalary: "Total kompensasi tahunan teknisi",
      warehouseManagerCount: "Jumlah admin gudang",
      warehouseManagerSalary: "Total kompensasi tahunan admin gudang",
      extraRoleName: "Nama peran tambahan",
      extraRoleCount: "Jumlah tenaga kerja tambahan",
      extraRoleSalary: "Total kompensasi tahunan peran tambahan",
      kmEnergyUse: "Konsumsi energi per km",
      energyPrice: "Tarif energi",
      oneWayDistance: "Jarak satu arah",
      repairHoursPerVisit: "Jam per perawatan",
      repairUnitPrice: "Tarif perawatan / jam",
      repairFrequency: "Frekuensi perawatan tahunan",
      tireUnitPrice: "Harga ban",
      tiresPerVehicle: "Jumlah ban per unit",
      tireReplacementFrequency: "Frekuensi penggantian ban",
      managementCount: "Jumlah manajemen",
      managementSalary: "Kompensasi tahunan rata-rata",
      facilityRent: "Biaya sewa lokasi tahunan",
      officeSpend: "Biaya kantor tahunan",
      partsCostMode: "Mode perhitungan biaya suku cadang",
      annualPartsDirectCost: "Proyeksi biaya suku cadang tahunan",
      infrastructurePurchaseValue: "Nilai perolehan infrastruktur sendiri",
      infrastructureValue: "Total nilai infrastruktur",
      partsSafetyRate: "Rasio safety stock suku cadang",
      tireSafetyRate: "Rasio safety stock ban",
      infrastructureDepreciationYears: "Masa depresiasi infrastruktur",
    },
    formulaCards: {
      operatingDays: "Hari operasi",
      payload: "Muatan per unit",
      dailyTrips: "Trip harian",
      attendanceRate: "Kehadiran",
      vehicleCount: "Jumlah unit",
      depreciationCost: "Biaya depresiasi",
      laborCost: "Biaya tenaga kerja",
      energyCost: "Biaya energi",
      partsCost: "Biaya suku cadang",
      repairCost: "Biaya servis",
      tireCost: "Biaya ban",
      operationCost: "Biaya operasional",
      infraAsset: "Infrastruktur",
      vehicleAsset: "Aset kendaraan",
      partsAsset: "Aset suku cadang",
      tireAsset: "Aset ban",
    },
    metrics: {
      operatingDays: "Hari operasi",
      payload: "Muatan per unit",
      dailyTrips: "Trip harian",
      attendanceRate: "Kehadiran",
      vehicleCount: "Jumlah unit",
      annualRevenue: "Total pendapatan 4 tahun",
      totalExpense: "Total biaya 4 tahun",
      totalAssets: "Total aset 4 tahun",
      lifecycleRoa: "ROA siklus hidup",
      loadVolume: "Volume muat",
      effectiveDailyHours: "Jam kerja efektif per hari",
      expectedDailyDemand: "Kebutuhan angkut harian",
    },
    notes: {
      moneyUnit: "Unit mata uang",
      report: "Catatan ekspor",
      roundUp: "Jumlah unit dibulatkan ke atas",
      fixedInfra: "Infrastruktur disusutkan garis lurus 10 tahun",
      averageAnnual: "Ditampilkan dengan dasar rata-rata 4 tahun",
    },
    table: {
      year: "Tahun",
      revenue: "Pendapatan",
      expense: "Biaya",
      profit: "Laba",
      assets: "Aset",
      roa: "ROA",
      infrastructure: "Nilai buku infrastruktur",
      partsAsset: "Aset suku cadang",
      tireAsset: "Aset ban",
      attendanceRate: "Kehadiran",
      annualTripsPerVehicle: "Trip tahunan per unit",
      lifecycle: "Siklus hidup",
      parameter: "Parameter",
      value: "Nilai",
      revenueModel: "Tabel Perhitungan Pendapatan Siklus Hidup",
      costModel: "Tabel Perhitungan Biaya Siklus Hidup",
      assetModel: "Tabel Perhitungan Aset Siklus Hidup",
      roaModel: "Tabel Perhitungan ROA Siklus Hidup",
      operationModel: "Tabel Efisiensi Operasional dan ROA",
      lifecycleParams: "Ringkasan Parameter Kunci Siklus Hidup",
    },
    groups: {
      revenuePricing: "Tarif angkut dan target volume",
      revenueOperatingDays: "Hari operasi",
      revenuePayload: "Muatan per unit",
      revenueTrips: "Ritase harian",
      revenueAttendance: "Tingkat kehadiran",
      revenueVehicles: "Jumlah unit",
      expenseDepreciation: "Biaya depresiasi",
      expenseLabor: "Biaya tenaga kerja",
      expenseEnergy: "Biaya energi",
      expenseParts: "Biaya suku cadang",
      expenseRepair: "Biaya perawatan",
      expenseTires: "Biaya ban",
      expenseOperations: "Biaya operasional",
      assetInfra: "Infrastruktur sendiri",
      assetVehicle: "Aset kendaraan",
      assetParts: "Aset suku cadang",
      assetTires: "Aset ban",
    },
    options: {
      calculated: "Hitung otomatis",
      manual: "Input manual",
      formula: "Hitung dari rincian suku cadang",
      direct: "Isi proyeksi tahunan langsung",
    },
    partRow: {
      name: "Nama suku cadang",
      quantity: "Jenis / jumlah",
      price: "Harga",
      frequency: "Frekuensi",
      add: "Tambah item",
      remove: "Hapus",
    },
    repeater: {
      addRoute: "Tambah rute / skenario",
      addContact: "Tambah kontak",
      addOrg: "Tambah struktur organisasi",
      addLaborRole: "Tambah peran",
    },
  },
};
